#!/bin/sh
set -e
#DEBHELPER#
case "$1" in
  purge|remove)
    if command -v update-initramfs >/dev/null 2>&1; then update-initramfs -u >/dev/null 2>&1 || true; fi
    if command -v update-grub >/dev/null 2>&1; then update-grub >/dev/null 2>&1 || true; fi
    ;;
esac
exit 0
